//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElefantesBlancosDatos
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class stra_acciones
    {
        public stra_acciones()
        {
            this.stra_auditoria = new HashSet<stra_auditoria>();
        }
    

        [Key]
        public int id_stra_accion { get; set; }
        public string nombre { get; set; }
    
        public  ICollection<stra_auditoria> stra_auditoria { get; set; }
    }
}
