//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package co.gov.presidencia.yocuidolopublico;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.util.Log;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.ListView;
import co.gov.mintic.util.ProgressDialogManager_;
import co.gov.presidencia.yocuidolopublico.service.client.CuidoLoPublicoClient_;
import co.gov.presidencia.yocuidolopublico.service.client.dto.CuidoLoPublicoTop5;
import co.gov.presidencia.yocuidolopublico.R.id;
import co.gov.presidencia.yocuidolopublico.R.layout;
import com.googlecode.androidannotations.api.BackgroundExecutor;

public final class TopCincoReportesActivity_
    extends TopCincoReportesActivity
{

    private Handler handler_ = new Handler();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.activity_top_cinco_reportes);
    }

    private void init_(Bundle savedInstanceState) {
        reportesClient = new CuidoLoPublicoClient_();
        dialog = ProgressDialogManager_.getInstance_(this);
    }

    private void afterSetContentView_() {
        topCinco = ((ListView) findViewById(id.topCinco));
        ((ProgressDialogManager_) dialog).afterSetContentView_();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    public static TopCincoReportesActivity_.IntentBuilder_ intent(Context context) {
        return new TopCincoReportesActivity_.IntentBuilder_(context);
    }

    @Override
    public void mostrarResultado(final CuidoLoPublicoTop5[] reportes) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    TopCincoReportesActivity_.super.mostrarResultado(reportes);
                } catch (RuntimeException e) {
                    Log.e("TopCincoReportesActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void showServerError() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    TopCincoReportesActivity_.super.showServerError();
                } catch (RuntimeException e) {
                    Log.e("TopCincoReportesActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void showConnectionError() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    TopCincoReportesActivity_.super.showConnectionError();
                } catch (RuntimeException e) {
                    Log.e("TopCincoReportesActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void obtenerReportes() {
        BackgroundExecutor.execute(new Runnable() {


            @Override
            public void run() {
                try {
                    TopCincoReportesActivity_.super.obtenerReportes();
                } catch (RuntimeException e) {
                    Log.e("TopCincoReportesActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, TopCincoReportesActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public TopCincoReportesActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
