//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElefantesBlancosDatos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class moviles4Entities : DbContext
    {
        public moviles4Entities()
            : base("name=moviles4Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
          //  throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<stra_departamentos> stra_departamentos { get; set; }
        public DbSet<stra_elefantes> stra_elefantes { get; set; }
        public DbSet<stra_estados_elefante> stra_estados_elefante { get; set; }
        public DbSet<stra_grupos> stra_grupos { get; set; }
        public DbSet<stra_imagenes> stra_imagenes { get; set; }
        public DbSet<stra_imagenes_temporal> stra_imagenes_temporal { get; set; }
        public DbSet<stra_motivos_elefante> stra_motivos_elefante { get; set; }
        public DbSet<stra_municipios> stra_municipios { get; set; }
        public DbSet<stra_rango_tiempo> stra_rango_tiempo { get; set; }
        public DbSet<stra_razones_rechazo> stra_razones_rechazo { get; set; }
        public DbSet<stra_regiones> stra_regiones { get; set; }
        public DbSet<stra_rutas> stra_rutas { get; set; }
        public DbSet<stra_usuarios> stra_usuarios { get; set; }
        public DbSet<stra_cantidad_elefantes_aprobados> stra_cantidad_elefantes_aprobados { get; set; }
        public DbSet<stra_cantidad_elefantes_pendientes> stra_cantidad_elefantes_pendientes { get; set; }
        public DbSet<stra_cantidad_imagenes_pendientes> stra_cantidad_imagenes_pendientes { get; set; }
        public DbSet<stra_departamentos_listado> stra_departamentos_listado { get; set; }
        public DbSet<stra_elefantes_detalle> stra_elefantes_detalle { get; set; }
        public DbSet<stra_municipios_listado> stra_municipios_listado { get; set; }
        public DbSet<stra_regiones_listado> stra_regiones_listado { get; set; }
        public DbSet<stra_total_nueva_informacion> stra_total_nueva_informacion { get; set; }
        public DbSet<stra_parametros> stra_parametros { get; set; }
    }
}
