//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElefantesBlancosDatos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class stra_municipios
    {
        public stra_municipios()
        {
            this.stra_elefantes = new HashSet<stra_elefantes>();
        }
    
        [Key]
        public string id_stra_municipio { get; set; }
        public string nombre { get; set; }
        public string id_stra_departamento { get; set; }
    
        public  stra_departamentos stra_departamentos { get; set; }
        public  ICollection<stra_elefantes> stra_elefantes { get; set; }
    }
}
