//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElefantesBlancosDatos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class stra_imagenes
    {
        public stra_imagenes()
        {
            //this.stra_elefantes = new HashSet<stra_elefantes>();
            //this.stra_elefantes1 = new HashSet<stra_elefantes>();
            //this.stra_imagenes_temporal = new HashSet<stra_imagenes_temporal>();
        }
    

        [Key]
        public int id_stra_imagen { get; set; }


         [Required(ErrorMessage = "El estado imagen es obligatorio")]
        public Nullable<sbyte> estado_imagen { get; set; }
        public Nullable<sbyte> tipo_imagen { get; set; }
        public Nullable<int> id_stra_imagen_asociada { get; set; }
        public Nullable<int> id_stra_razon_rechazo { get; set; }
        public string razon_rechazo { get; set; }
        public Nullable<int> id_stra_elefante { get; set; }

        //public virtual ICollection<stra_elefantes> stra_elefantes { get; set; }
        //public virtual ICollection<stra_elefantes> stra_elefantes1 { get; set; }
        public  stra_elefantes stra_elefantes2 { get; set; }
        public  ICollection<stra_imagenes_temporal> stra_imagenes_temporal { get; set; }
        public  stra_razones_rechazo stra_razones_rechazo { get; set; }
    }
}
