//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElefantesBlancosDatos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class stra_imagenes_temporal
    {

        [Key]
        public int id_stra_imagen_temporal { get; set; }
        public int id_stra_imagen { get; set; }
        public byte[] imagen { get; set; }
        public int id_stra_elefante { get; set; }
        public sbyte tipo_imagen { get; set; }
    
        public  stra_elefantes stra_elefantes { get; set; }
        public  stra_imagenes stra_imagenes { get; set; }
    }
}
