//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElefantesBlancosDatos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class stra_departamentos
    {
        public stra_departamentos()
        {
            //this.stra_elefantes = new HashSet<stra_elefantes>();
            //this.stra_municipios = new HashSet<stra_municipios>();
        }
    
        [Key]
        public string id_stra_departamento { get; set; }
        public string nombre { get; set; }
        public int id_stra_region { get; set; }
    
        //public virtual stra_regiones stra_regiones { get; set; }
        //public virtual ICollection<stra_elefantes> stra_elefantes { get; set; }
        //public virtual ICollection<stra_municipios> stra_municipios { get; set; }
    }
}
