//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElefantesBlancosDatos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class stra_elefantes
    {
        public stra_elefantes()
        {
            this.stra_imagenes_temporal = new HashSet<stra_imagenes_temporal>();
            this.stra_imagenes2 = new HashSet<stra_imagenes>();
        }



        [Key]
        public int id_stra_elefante { get; set; }
        [Required(ErrorMessage = "El título es obligatorio")]
        [StringLength(100, ErrorMessage = "Máximo número de caracteres sobrepasado")]
        public string titulo { get; set; }
        [Required(ErrorMessage = "Debe aprobar o no aprobar el titulo")]
        public Nullable<sbyte> estado_titulo { get; set; }
        [DataType(DataType.MultilineText)]
        [Required(ErrorMessage = "La entidad responsable es obligatorio")]
        [StringLength(100, ErrorMessage = "Máximo número de caracteres sobrepasado")]
        public string entidad_responsable { get; set; }
        [Required(ErrorMessage = "Debe aprobar o no aprobar la entidad responsable")]
        public Nullable<sbyte> estado_entidad { get; set; }
        [Required(ErrorMessage = "El porque es un elefante es obligatorio")]
        public int id_stra_motivo_elefante { get; set; }
        [Required(ErrorMessage = "Debe aprobar o no aprobar el porque es un elefante")]
        public Nullable<sbyte> estado_id_motivo_elefante { get; set; }
        [Required(ErrorMessage = "Debe aprobar o no aprobar la foto")]
        public Nullable<sbyte> estado_imagen { get; set; }
        public Nullable<int> id_stra_rango_tiempo { get; set; }
        public Nullable<sbyte> estado_id_rango_tiempo { get; set; }
        [RegularExpression("([0-9]*)", ErrorMessage = "El costo debe ser numérico")]
        public Nullable<long> costo { get; set; }
        public Nullable<sbyte> estado_costo { get; set; }
        [StringLength(100, ErrorMessage = "Máximo número de caracteres sobrepasado")]
        public string contratista { get; set; }
        public Nullable<sbyte> estado_contratista { get; set; }
        public Nullable<int> id_stra_imagen_principal_grande { get; set; }
        public Nullable<int> id_stra_imagen_principal_pequena { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public string id_stra_municipio { get; set; }
        public int id_stra_estado_elefante { get; set; }
        public string id_stra_departamento { get; set; }
        public int id_stra_region { get; set; }
        public bool no_es_un_elefante { get; set; }
        public Nullable<int> id_stra_razon_rechazo { get; set; }
        public string comentario_rechazo { get; set; }
        public string direccion { get; set; }
        public double latitud { get; set; }
        public double longitud { get; set; }
        public int cantidad_rechazos { get; set; }


        public  stra_departamentos stra_departamentos { get; set; }
        public  ICollection<stra_imagenes_temporal> stra_imagenes_temporal { get; set; }
        public  stra_estados_elefante stra_estados_elefante { get; set; }

        //[ForeignKey("id_stra_imagen")]
        //public  int id_stra_imagen { get; set; }


       //[ForeignKey("id_stra_imagen")]
       // public virtual stra_imagenes stra_imagenes { get; set; }

       ////[ForeignKey("IdStrImagen1")]
       // public virtual stra_imagenes stra_imagenes1 { get; set; }
        public  stra_motivos_elefante stra_motivos_elefante { get; set; }
        public  stra_municipios stra_municipios { get; set; }
        public  stra_rango_tiempo stra_rango_tiempo { get; set; }
        public  stra_razones_rechazo stra_razones_rechazo { get; set; }
        public  stra_regiones stra_regiones { get; set; }
        public  ICollection<stra_imagenes> stra_imagenes2 { get; set; }
    }
}
