//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElefantesBlancosDatos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class stra_regiones
    {
        public stra_regiones()
        {
            this.stra_departamentos = new HashSet<stra_departamentos>();
            this.stra_elefantes = new HashSet<stra_elefantes>();
        }
    
        [Key]
        public int id_stra_region { get; set; }
        public string nombre { get; set; }
    
        public  ICollection<stra_departamentos> stra_departamentos { get; set; }
        public  ICollection<stra_elefantes> stra_elefantes { get; set; }
    }
}
