//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElefantesBlancosDatos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class stra_grupos
    {
        public stra_grupos()
        {
            this.stra_usuarios = new HashSet<stra_usuarios>();
        }
    
        [Key]
        public int id_stra_grupo { get; set; }
        public string descripcion { get; set; }
    
        public  ICollection<stra_usuarios> stra_usuarios { get; set; }
    }
}
