//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElefantesBlancosDatos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class stra_elefantes_detalle
    {
        [Key]
        public int id_stra_elefante { get; set; }
        public string titulo { get; set; }
        public bool no_es_un_elefante { get; set; }
        [DataType(DataType.DateTime)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public System.DateTime fecha_creacion { get; set; }
        public string id_stra_departamento { get; set; }
        public int id_stra_region { get; set; }
        public string id_stra_municipio { get; set; }
        public string departamento { get; set; }
        public string municipio { get; set; }
        public int id_stra_estado_elefante { get; set; }
        public string estado { get; set; }
        public Nullable<int> id_stra_imagen_principal_pequena { get; set; }
        public Nullable<int> id_stra_imagen_principal_grande { get; set; }
        public Nullable<int> imagenpendiente { get; set; }
        public int cantidadarangotiempo { get; set; }
        public int cantidadcosto { get; set; }
        public int cantidadcontratista { get; set; }
        //Propiedades adicionales
        public string ruta { get; set; }
        public bool EsInformacion { get; set; }
        public bool EsImagen { get; set; }
        public List<DepartamentoModels> ListDepartamentoModels { get; set; }
    }
}
